### ISSUE TITLE
[Enhancement] Configurable Active Guard Penalty

### ISSUE THREAD

**Issue by falconfruitpunch1** [CravenCraft/EpicParagliders#16]
I've been trying to encourage offensive play lately for a modpack, and this mod has been a huge help.
To better balance guarding, though, the option to set a custom stamina penalty multiplier (positive or negative) for Active Guards when the skill is applied would be a huge help.

**Comment by CravenCraft** [comment]
You mean you want to be able to customize both the successful and unsuccessful active guard results to be either a positive or negative value?

**Comment by falconfruitpunch1** [comment]
Moreso the successful Active Guard in addition to the preexisting Guard, but extra customization is always helpful.
Presently I'm aiming to make a Sekiro-style deflection system, in which regular Guarding has a multiplier of around 2x stamina cost, and Active Guards have only a 0.5x multiplier.

**Comment by CravenCraft** [comment]
When I release my new version to the latest version of EFM I'll have this config option! I've already coded and tested the changes and it should work exactly the way you want it to. You'll just have to tweak the config options of the default guard and active guard a bit to your liking.
