### ISSUE TITLE
blood and madness compatibility

### ISSUE THREAD

**Issue by ZIDCAKE** [CravenCraft/EpicParagliders#19]
In the latest version of the blood and madness mod, it is possible to upgrade weapons up to +10.
However, with each weapon upgrade, the stamina consumption increases. If a weapon is upgraded to +10, then all stamina is consumed in one hit

I couldn't find any information on this compatibility. Is there a way to fix this?
There is also an idea to add functionality that is controlled through the config - for example, a sword is enchanted to sharpness 5, which increases stamina consumption

**Comment by ZIDCAKE** [comment]
Oh, I get it. The principle here is that the more damage a weapon does, the more stamina is spent.
Can you tell me how to control that?

**Comment by ZIDCAKE** [comment]
Oh, I get it. The principle here is that the more damage a weapon does, the more stamina is spent.
Can you tell me how to control that?

**Comment by CravenCraft** [comment]
Yep! So, you can do one of two things:
 
1.) edit the server config for that particular weapon type's multiplier to drain less, but the drawback there is that it affects all weapons of that type.

2.) probably the option you're looking for. I now have the option to edit epic fight datapacks. So, you can add in an attribute for your specific weapon. Check out my README for an example on how to do that

**Comment by ZIDCAKE** [comment]
Understood thanks!
