### ISSUE TITLE
Epic Paragliders Not Compatible With Newest Version Of Epic Fight

### ISSUE THREAD

**Issue by BoatTK** [CravenCraft/EpicParagliders#26]
Hello,
I'm in a creative test world right now, and Stamina Pillager does not seem to be giving me the passive 30% stamina boost when I kill an enemy. I had thought I might be using too much stamina when the effect applies, but even on max stamina with a wooden sword, I am regaining no stamina. (This is for the newest 1.18.2 version, and I am using Epic Fight's stamina bar)

**Comment by BoatTK** [comment]
Hello,
This seems to have been a problem with Epic Fight that was fixed, however, using the new version leads to an Error when using weapons: java.lang.NoClassDefFoundError: yesman/epicfight/world/item/KnuckleItem
	at net.cravencraft.epicparagliders.utils.MathUtils.getAttackStaminaCost(MathUtils.java:54) ~[epicparagliders-0.5.1-1.18.2.jar%2369!/:0.5.1-1.18.2] {re:mixin,re:classloading}

**Comment by CravenCraft** [comment]
Gotcha. I'll take a look into that. Looks like I just might have missed something super small with the knuckle weapon item

**Comment by BoatTK** [comment]
Upon further inspection, this crash happens when you use attack with:
Bare hands
Taichi
Spear
Greatsword
Uchigatana
Sword
The only weapon type it doesn't crash with is daggers. No matter which weapon is used, the error message always cites the KunckleItem.
I've attached a crash report as well.
[crash-2023-11-29_22.41.32-server.txt](https://github.com/CravenCraft/EpicParagliders/files/13508108/crash-2023-11-29_22.41.32-server.txt)

**Comment by CravenCraft** [comment]
I'll be submitting V0.6.0 of my mod to curseforge sometime later today. Hopefully that fixes the issue. I'll say that I haven't tested this with the newest 18.5.18 version of Epic Fight. It added a new skill that I'll need to take a look at sometime in the future to support. So, for now just use Epic Fight 18.5.17
